### ISSUE TITLE
Ship all available information with the i3 events.

### ISSUE THREAD

**Issue by mox-mox** [drmgc/i3ipcpp#2]
When receiving i3 events, some information, like the "current" and "old" properties of the workspace event are not passed on.
Could you please add a way to access the missing properties/information when receiving an event?

**Comment by drmgc** [comment]
I warn you: it would break backward compatibility

**Comment by drmgc** [comment]
Please test it, if you can.

**Comment by mox-mox** [comment]
First of all, big thanks for adding the information.
For me, it seems to work with one small exception:
I3 will report border = pixel if the setting "new_window pixel" is used. With me, this raises errors for all windows that use this style.

**Comment by drmgc** [comment]
Create an issue, please

**Comment by drmgc** [comment]
@mox-mox also, if you getting in `border` field value, that not expected by i3ipc++, you could recognize it from `border`, that would equals `BorderStyle::UNKNOWN`, and `border_raw` field of `container_t`, that in the case of `BorderStyle::UNKNOWN` would contain a value of `border` field, recived from i3

**Comment by drmgc** [comment]
@mox-mox also, there is no one word about `pixel` border style in documentation:
![099](https://cloud.githubusercontent.com/assets/4511609/14841658/a772ed3e-0c48-11e6-93ef-6dffcddf8c86.png)
There is also few new features, that I can't implemente dut to the fact, that I use Debian 8, so:

```
i3 version 4.8 (2014-06-15, branch "4.8") © 2009-2014 Michael Stapelberg and contributors
```
