### ISSUE TITLE
Example of passing a command with quotes to i3

### ISSUE THREAD

**Issue by kgilmer** [drmgc/i3ipcpp#25]
Thanks for your library, it certainly makes integrating with i3 much easier!  :)

I am trying to create a program that manages window containment in i3.  I wish to pass commands to i3 to move workspaces and windows around.  However when I try to pass any commands with escaped quotations, I get a parse error back from i3.  I cannot find an example that passes a command to i3 w/ quotes and would like to know how to do this.

For example, I can run the following command succesfully:
```
$ i3-msg '[workspace=" 2 <span foreground='#2aa198'></span> "]' move workspace to output eDP-1
[{"success":true}]
```

However when I pass the string `"'[workspace=" 2 <span foreground='#2aa198'></span> "]' move workspace to output eDP-1"` to i3 via  `bool  connection::send_command(const std::string&  command) const` I get the general "expecting token" error from i3.

Expected results: I can pass commands with backslash-escaped quotes to i3 via send_command()
Actual results: I get a parse error for any escaped string in a command

**Comment by drmgc** [comment]
I am glad that the library is useful to you)
It seems to be issue of JsonCpp using, but I am not really sure. I'll check the code in few days, but could you, please, give some more context: output, your code and so on

**Comment by kgilmer** [comment]
Sure, I have workspace names with spaces in them.  I have a [program](https://github.com/regolith-linux/i3-snapshot) that tries to move workspaces to outputs based on file input.  When I run the same command I pass via `i3-msg` on the command line with i3ipcpp, I get the general syntax error.  The move command specifics are in the initial bug report.  If I use workspaces without spaces (and therefor do not have to enclose it with quotes) there is no problem with i3ipcpp or i3wm.

**Comment by drmgc** [comment]
Well, if pass the string without `'` around `[` and `]`, i. e.:
```C++
if (conn.send_command("[workspace=\" 2 <span foreground='#2aa198'></span> \"] move workspace to output eDP-1")) {
	std::cout << "Success" << std::endl;
}
```
then it succeeds

**Comment by kgilmer** [comment]
Yes, you're right.  I guess I didn't try that variation.  Thanks for your help @drmgc , i can simplify my program now as I don't have to track both workspace name and container id.
