### ISSUE TITLE
W: Got a unknown "border" property: "pixel".

### ISSUE THREAD

**Issue by mox-mox** [drmgc/i3ipcpp#7]
When setting "new window pixel 1" in the i3config, i3 will send "border" : "pixel" as border style in the tree reply.
Example:
{
    "border" : "pixel",
    "current_border_width" : -1,
    "deco_rect" : 
    {
        "height" : 0,
        "width" : 0,
        "x" : 0,
        "y" : 0
    },
    "floating" : "auto_off",
    "floating_nodes" : [],
    "focus" : [],
    "focused" : false,
    "fullscreen_mode" : 0,
    "geometry" : 
    {
        "height" : 0,
        "width" : 0,
        "x" : 0,
        "y" : 0
    },
    "id" : 31099360,
    "last_split_layout" : "splith",
    "layout" : "dockarea",
    "name" : "bottomdock",
    "nodes" : [],
    "orientation" : "none",
    "percent" : null,
    "rect" : 
    {
        "height" : 0,
        "width" : 1600,
        "x" : 0,
        "y" : 900
    },
    "scratchpad_state" : "none",
    "sticky" : false,
    "swallows" : 
    [
        {
            "dock" : 3,
            "insert_where" : 2
        }
    ],
    "type" : "dockarea",
    "urgent" : false,
    "window" : null,
    "window_rect" : 
    {
        "height" : 0,
        "width" : 0,
        "x" : 0,
        "y" : 0
    },
    "workspace_layout" : "default"
}

**Comment by mox-mox** [comment]
Pull request #6 proposes a fix for this issue.

**Comment by drmgc** [comment]
@mox-mox, is it resolved now?

**Comment by mox-mox** [comment]
Yes, thank you very much :)
